name: MakiMoki-Android

on:
  push:
    branches:
      - android
#    tags:
#      - 'period-android-*'
  pull_request:
    branches:
      - android
#  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest 
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      Solution_Name: MakiMoki.Droid.sln
      Wap_Project_Directory: ""
      Wap_Project_Path: src/android/MakiMoki.Droid/MakiMoki.Droid.csproj 
      Wap_Publish_Output: publish
      Wap_Publish_Apk: futaba-makimoki/src/android/MakiMoki.Droid/publish/net.yarukizero.makimoki.android.dev-Signed.apk
      Wap_Version_ConfFile: src/wpf/MakiMoki.Wpf/Properties/publish.conf.json
      App_Center_Group: Canary
      Artifact_Conf: publish/appcenter.conf.json    
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Print Config
      run: |
        echo "GITHUB_REPOSITORY=$env:GITHUB_REPOSITORY"
        echo "GITHUB_EVENT_NAME=$env:GITHUB_EVENT_NAME"
        echo "GITHUB_REF=$env:GITHUB_REF"

    - name: Put KEYSTORE
      run: |
        $b = [System.Convert]::FromBase64String($env:keystore)
        [System.IO.File]::WriteAllBytes("$pwd\github.keystore", $b)
      env:
        keystore: ${{ secrets.DROID_CANARY_KEYSTORE }}

    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Install Workload Android
      run: |
        dotnet workload install android

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1

    - name: Restore the application
      run: |
        msbuild `
          -t:Restore `
          -p:Configuration=Release `
          $env:Solution_Name

    - name: Exec T4
      run: |
        msbuild `
          -t:TransformAll `
          -m `
          -p:Configuration=T4Release `
          -p:Github=True `
          $env:Solution_Name

    - name: Build app
      run: |
        msbuild $env:Wap_Project_Path `
          -m `
          -verbosity:normal `
          -t:Rebuild `
          -t:PackageForAndroid `
          -t:SignAndroidPackage `
          -p:OutDir=$env:Wap_Publish_Output `
          -p:Configuration=Release `
          -p:AndroidKeyStore=True `
          "-p:AndroidSigningKeyStore=$pwd\github.keystore" `
          -p:AndroidSigningStorePass=$env:pass_store `
          -p:AndroidSigningKeyAlias=github `
          -p:AndroidSigningKeyPass=$env:pass_key `
          -p:AndroidPackageFormat=apk `
          -p:AotAssemblies=true `
          -p:EnableLLVM=true
      env:
        pass_store: ${{ secrets.DROID_CANARY_PASS_STORE }}
        pass_key: ${{ secrets.DROID_CANARY_PASS_KEY }}

    - name: Install node
      uses: actions/setup-node@v1
      with:
        node-version: 16.x

    - name: Upload Artefact to App Center
      run: |
        npx appcenter-cli distribute release `
          --disable-telemetry `
          --token ${token} `
          -f "$pwd/$env:Wap_Publish_Apk" `
          -g $env:App_Center_Group `
          -b "build.$env:build" `
          -a azumyar/doromaki
      env:
        build: ${{ github.run_number }}
        token: ${{ secrets.APP_CENTER_TOKEN }}

#   - name: Archive Zip
#      run: |
#        del $pwd\github.keystore
#        Compress-Archive -Path $pwd -DestinationPath "output.zip"
#
#    - name: Upload Artifact
#      uses: actions/upload-artifact@v2
#      with:
#        name: "test.zip"
#        path: "output.zip"
#        retention-days: 7

